title: Hafiz Samiullah # your name (or website title) here
logo: "/images/urc.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Machine Learning & AI Engineer | Data Scientist | Computer Vision Engineer
  <br><br>
  
  <a href="https://www.linkedin.com/in/hsamiullah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-64YT8FEYF8 # your Google Analytics tracking ID here
