title: Samiullah # your name (or website title) here
logo: "/images/urc.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sofware Developer | Data Scientist | Computer Vision & AI Expert
  <br><br>
  Electrical & Electronics Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/hafiz-sami-ullah-18474a111/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-64YT8FEYF8 # your Google Analytics tracking ID here
